include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - require_trailing_commas
    - sized_box_for_whitespace
    - prefer_const_constructors
    - prefer_single_quotes
    - prefer_final_locals
    - prefer_final_in_for_each

analyzer:
  exclude:
    - lib/**.g.dart
    - lib/**.config.dart
    - lib/**.freezed.dart