import 'package:blueprint/utils/appearance/appearance_library.dart';
import 'package:flutter/material.dart';

ColorScheme get colorScheme {
  return const ColorScheme(
    brightness: Brightness.light,
    primary: AppColorsLight.primary,
    onPrimary: AppColorsLight.onPrimary,
    primaryContainer: AppColorsLight.primaryContainer,
    onPrimaryContainer: AppColorsLight.onPrimaryContainer,
    secondary: AppColorsLight.secondary,
    onSecondary: AppColorsLight.onSecondary,
    secondaryContainer: AppColorsLight.secondaryContainer,
    onSecondaryContainer: AppColorsLight.onSecondaryContainer,
    tertiary: AppColorsLight.tertiary,
    onTertiary: AppColorsLight.onTertiary,
    tertiaryContainer: AppColorsLight.tertiaryContainer,
    onTertiaryContainer: AppColorsLight.onTertiaryContainer,
    error: AppColorsLight.error,
    onError: AppColorsLight.error,
    errorContainer: AppColorsLight.errorContainer,
    onErrorContainer: AppColorsLight.onErrorContainer,
    background: AppColorsLight.background,
    onBackground: AppColorsLight.onBackground,
    surface: AppColorsLight.surface,
    onSurface: AppColorsLight.onSurface,
    surfaceVariant: AppColorsLight.surfaceVariant,
    onSurfaceVariant: AppColorsLight.onSurfaceVariant,
    outline: AppColorsLight.outline,
    outlineVariant: AppColorsLight.outlineVariant,
    inverseSurface: AppColorsLight.inverseSurface,
    onInverseSurface: AppColorsLight.onInverseSurface,
    inversePrimary: AppColorsLight.inversePrimary,
    surfaceTint: AppColorsLight.surfaceTint,
  );
}

ColorScheme get colorSchemeDark {
  return const ColorScheme(
    brightness: Brightness.dark,
    primary: AppColorsDark.primary,
    onPrimary: AppColorsDark.onPrimary,
    primaryContainer: AppColorsDark.primaryContainer,
    onPrimaryContainer: AppColorsDark.onPrimaryContainer,
    secondary: AppColorsDark.secondary,
    onSecondary: AppColorsDark.onSecondary,
    secondaryContainer: AppColorsDark.secondaryContainer,
    onSecondaryContainer: AppColorsDark.onSecondaryContainer,
    tertiary: AppColorsDark.tertiary,
    onTertiary: AppColorsDark.onTertiary,
    tertiaryContainer: AppColorsDark.tertiaryContainer,
    onTertiaryContainer: AppColorsDark.onTertiaryContainer,
    error: AppColorsDark.error,
    onError: AppColorsDark.error,
    errorContainer: AppColorsDark.errorContainer,
    onErrorContainer: AppColorsDark.onErrorContainer,
    background: AppColorsDark.background,
    onBackground: AppColorsDark.onBackground,
    surface: AppColorsDark.surface,
    onSurface: AppColorsDark.onSurface,
    surfaceVariant: AppColorsDark.surfaceVariant,
    onSurfaceVariant: AppColorsDark.onSurfaceVariant,
    outline: AppColorsDark.outline,
    outlineVariant: AppColorsDark.outlineVariant,
    inverseSurface: AppColorsDark.inverseSurface,
    onInverseSurface: AppColorsDark.onInverseSurface,
    inversePrimary: AppColorsDark.inversePrimary,
    surfaceTint: AppColorsDark.surfaceTint,
  );
}
