final rawCountries = <Map<String, dynamic>>[
  {
    'name': 'Qatar',
    'isoCode': 'QA',
    'phoneCode': '+974',
    'mask': '#### ####',
    'minLength': 8,
  },
  {
    'name': 'Vanuatu',
    'isoCode': 'VU',
    'phoneCode': '+678',
    'mask': '## #####',
    'minLength': 5,
  },
  {
    'name': 'Gambia',
    'isoCode': 'GM',
    'phoneCode': '+220',
    'mask': '### ## ##',
    'minLength': 7,
  },
  {
    'name': 'Nauru',
    'isoCode': 'NR',
    'phoneCode': '+674',
    'mask': '### ####',
    'minLength': 7,
  },
  {
    'name': 'Lesotho',
    'isoCode': 'LS',
    'phoneCode': '+266',
    'mask': '# ### ####',
    'minLength': 8,
  },
  {
    'name': 'Finland',
    'isoCode': 'FI',
    'phoneCode': '+358',
    'mask': '### ### ## ##',
    'minLength': 10,
  },
  {
    'name': 'Tonga',
    'isoCode': 'TO',
    'phoneCode': '+676',
    'mask': '#####',
    'minLength': 5,
  },
  {
    'name': 'Latvia',
    'isoCode': 'LV',
    'phoneCode': '+371',
    'mask': '## ### ###',
    'minLength': 8,
  },
  {
    'name': 'Costa Rica',
    'isoCode': 'CR',
    'phoneCode': '+506',
    'mask': '#### ####',
    'minLength': 8,
  },
  {
    'name': 'Holy See',
    'isoCode': 'VA',
    'phoneCode': '+39',
    'mask': '#####',
    'minLength': 5,
  },
  {
    'name': 'New Caledonia',
    'isoCode': 'NC',
    'phoneCode': '+687',
    'mask': '## ####',
    'minLength': 6,
  },
  {
    'name': 'Denmark',
    'isoCode': 'DK',
    'phoneCode': '+45',
    'mask': '## ## ## ##',
    'minLength': 8,
  },
  {
    'name': 'Saint Martin',
    'isoCode': 'MF',
    'phoneCode': '+590',
    'mask': '### ### ###',
    'minLength': 9,
  },
  {
    'name': 'Switzerland',
    'isoCode': 'CH',
    'phoneCode': '+41',
    'mask': '## ### ####',
    'minLength': 9,
  },
  {
    'name': 'Réunion',
    'isoCode': 'RE',
    'phoneCode': '+262',
    'mask': '##### ####',
    'minLength': 9,
  },
  {
    'name': 'Samoa',
    'isoCode': 'WS',
    'phoneCode': '+685',
    'mask': '## ####',
    'minLength': 6,
  },
  {
    'name': 'North Macedonia',
    'isoCode': 'MK',
    'phoneCode': '+389',
    'mask': '## ### ###',
    'minLength': 8,
  },
  {
    'name': 'Cameroon',
    'isoCode': 'CM',
    'phoneCode': '+237',
    'mask': '#### ####',
    'minLength': 8,
  },
  {
    'name': 'Albania',
    'isoCode': 'AL',
    'phoneCode': '+355',
    'mask': '### ### ###',
    'minLength': 9,
  },
  {
    'name': 'Germany',
    'isoCode': 'DE',
    'phoneCode': '+49',
    'mask': '#### ### ####',
    'minLength': 6,
  },
  {
    'name': 'Suriname',
    'isoCode': 'SR',
    'phoneCode': '+597',
    'mask': '### ####',
    'minLength': 6,
  },
  {
    'name': 'Tuvalu',
    'isoCode': 'TV',
    'phoneCode': '+688',
    'mask': '####',
    'minLength': 4,
  },
  {
    'name': 'Anguilla',
    'isoCode': 'AI',
    'phoneCode': '+1264',
    'mask': '### ####',
    'minLength': 7,
  },
  {
    'name': 'Serbia',
    'isoCode': 'RS',
    'phoneCode': '+381',
    'mask': '## ### ####',
    'minLength': 9,
  },
  {
    'name': 'Turkmenistan',
    'isoCode': 'TM',
    'phoneCode': '+993',
    'mask': '# ### ####',
    'minLength': 8,
  },
  {
    'name': 'Bosnia and Herzegovina',
    'isoCode': 'BA',
    'phoneCode': '+387',
    'mask': '## #####',
    'minLength': 6,
  },
  {
    'name': 'Ukraine',
    'isoCode': 'UA',
    'phoneCode': '+380',
    'mask': '## ### ## ##',
    'minLength': 9,
  },
  {
    'name': 'Lithuania',
    'isoCode': 'LT',
    'phoneCode': '+370',
    'mask': '### ## ###',
    'minLength': 8,
  },
  {
    'name': 'Afghanistan',
    'isoCode': 'AF',
    'phoneCode': '+93',
    'mask': '## ### ####',
    'minLength': 9,
  },
  {
    'name': 'Saint Helena, Ascension and Tristan da Cunha',
    'isoCode': 'SH',
    'phoneCode': '+290',
    'mask': '####',
    'minLength': 4,
  },
  {
    'name': 'Jamaica',
    'isoCode': 'JM',
    'phoneCode': '+1876',
    'mask': '### ####',
    'minLength': 7,
  },
  {
    'name': 'Mozambique',
    'isoCode': 'MZ',
    'phoneCode': '+258',
    'mask': '## ### ###',
    'minLength': 8,
  },
  {
    'name': 'Bangladesh',
    'isoCode': 'BD',
    'phoneCode': '+880',
    'mask': '### ######',
    'minLength': 9,
  },
  {
    'name': 'San Marino',
    'isoCode': 'SM',
    'phoneCode': '+378',
    'mask': '#### ######',
    'minLength': 10,
  },
  {
    'name': 'Aland Islands',
    'isoCode': 'AX',
    'phoneCode': '+358',
    'mask': '### ### ## ##',
    'minLength': 10,
  },
  {
    'name': 'Panama',
    'isoCode': 'PA',
    'phoneCode': '+507',
    'mask': '### ####',
    'minLength': 7,
  },
  {
    'name': 'Kazakhstan',
    'isoCode': 'KZ',
    'phoneCode': '+7',
    'mask': '## ### ## ##',
    'minLength': 9,
  },
  {
    'name': 'Russia',
    'isoCode': 'RU',
    'phoneCode': '+7',
    'mask': '### ### ## ##',
    'minLength': 10,
  },
  {
    'name': 'Moldova',
    'isoCode': 'MD',
    'phoneCode': '+373',
    'mask': '#### ####',
    'minLength': 8,
  },
  {
    'name': 'Greenland',
    'isoCode': 'GL',
    'phoneCode': '+299',
    'mask': '## ## ##',
    'minLength': 6,
  },
  {
    'name': 'Gibraltar',
    'isoCode': 'GI',
    'phoneCode': '+350',
    'mask': '### #####',
    'minLength': 8,
  },
  {
    'name': 'Argentina',
    'isoCode': 'AR',
    'phoneCode': '+54',
    'mask': '### ### ####',
    'minLength': 10,
  },
  {
    'name': 'Oman',
    'isoCode': 'OM',
    'phoneCode': '+968',
    'mask': '## ### ###',
    'minLength': 8,
  },
  {
    'name': 'Greece',
    'isoCode': 'GR',
    'phoneCode': '+30',
    'mask': '### ### ####',
    'minLength': 10,
  },
  {
    'name': 'Bahrain',
    'isoCode': 'BH',
    'phoneCode': '+973',
    'mask': '#### ####',
    'minLength': 8,
  },
  {
    'name': 'Kenya',
    'isoCode': 'KE',
    'phoneCode': '+254',
    'mask': '### ######',
    'minLength': 9,
  },
  {
    'name': 'Estonia',
    'isoCode': 'EE',
    'phoneCode': '+372',
    'mask': '#### ####',
    'minLength': 7,
  },
  {
    'name': 'Saint Pierre and Miquelon',
    'isoCode': 'PM',
    'phoneCode': '+508',
    'mask': '## ####',
    'minLength': 6,
  },
  {
    'name': 'Saint Kitts and Nevis',
    'isoCode': 'KN',
    'phoneCode': '+1869',
    'mask': '### ####',
    'minLength': 7,
  },
  {
    'name': 'Svalbard and Jan Mayen',
    'isoCode': 'SJ',
    'phoneCode': '+47',
    'mask': '### ## ###',
    'minLength': 8,
  },
  {
    'name': 'Haiti',
    'isoCode': 'HT',
    'phoneCode': '+509',
    'mask': '## ## ####',
    'minLength': 8,
  },
  {
    'name': 'Philippines',
    'isoCode': 'PH',
    'phoneCode': '+63',
    'mask': '### ### ####',
    'minLength': 10,
  },
  {
    'name': 'Belarus',
    'isoCode': 'BY',
    'phoneCode': '+375',
    'mask': '## ### ## ##',
    'minLength': 9,
  },
  {
    'name': 'Georgia',
    'isoCode': 'GE',
    'phoneCode': '+995',
    'mask': '### ### ###',
    'minLength': 9,
  },
  {
    'name': 'Ethiopia',
    'isoCode': 'ET',
    'phoneCode': '+251',
    'mask': '## ### ####',
    'minLength': 9,
  },
  {
    'name': 'Papua New Guinea',
    'isoCode': 'PG',
    'phoneCode': '+675',
    'mask': '### ## ###',
    'minLength': 8,
  },
  {
    'name': 'Guinea',
    'isoCode': 'GN',
    'phoneCode': '+224',
    'mask': '## ### ###',
    'minLength': 8,
  },
  {
    'name': 'Indonesia',
    'isoCode': 'ID',
    'phoneCode': '+62',
    'mask': '## ### ## ###',
    'minLength': 7,
  },
  {
    'name': 'Niue',
    'isoCode': 'NU',
    'phoneCode': '+683',
    'mask': '####',
    'minLength': 4,
  },
  {
    'name': 'Guatemala',
    'isoCode': 'GT',
    'phoneCode': '+502',
    'mask': '# ### ####',
    'minLength': 8,
  },
  {
    'name': 'Taiwan',
    'isoCode': 'TW',
    'phoneCode': '+886',
    'mask': '# #### ####',
    'minLength': 8,
  },
  {
    'name': 'Tajikistan',
    'isoCode': 'TJ',
    'phoneCode': '+992',
    'mask': '## ### ####',
    'minLength': 9,
  },
  {
    'name': 'India',
    'isoCode': 'IN',
    'phoneCode': '+91',
    'mask': '#### ### ###',
    'minLength': 10,
  },
  {
    'name': 'Nepal',
    'isoCode': 'NP',
    'phoneCode': '+977',
    'mask': '## ### ###',
    'minLength': 8,
  },
  {
    'name': 'Ecuador',
    'isoCode': 'EC',
    'phoneCode': '+593',
    'mask': '## ### ####',
    'minLength': 8,
  },
  {
    'name': 'Luxembourg',
    'isoCode': 'LU',
    'phoneCode': '+352',
    'mask': '### ### ###',
    'minLength': 9,
  },
  {
    'name': 'Rwanda',
    'isoCode': 'RW',
    'phoneCode': '+250',
    'mask': '### ### ###',
    'minLength': 9,
  },
  {
    'name': 'Malaysia',
    'isoCode': 'MY',
    'phoneCode': '+60',
    'mask': '### ### ###',
    'minLength': 7,
  },
  {
    'name': 'France',
    'isoCode': 'FR',
    'phoneCode': '+33',
    'mask': '### ### ###',
    'minLength': 9,
  },
  {
    'name': 'Chad',
    'isoCode': 'TD',
    'phoneCode': '+235',
    'mask': '## ## ## ##',
    'minLength': 8,
  },
  {
    'name': 'Norfolk Island',
    'isoCode': 'NF',
    'phoneCode': '+672',
    'mask': '## ###',
    'minLength': 5,
  },
  {
    'name': 'Uzbekistan',
    'isoCode': 'UZ',
    'phoneCode': '+998',
    'mask': '## ### ####',
    'minLength': 9,
  },
  {
    'name': 'Monaco',
    'isoCode': 'MC',
    'phoneCode': '+377',
    'mask': '### ### ###',
    'minLength': 8,
  },
  {
    'name': 'Cuba',
    'isoCode': 'CU',
    'phoneCode': '+53',
    'mask': '# ### ####',
    'minLength': 8,
  },
  {
    'name': 'Austria',
    'isoCode': 'AT',
    'phoneCode': '+43',
    'mask': '### ### ####',
    'minLength': 10,
  },
  {
    'name': 'Dominica',
    'isoCode': 'DM',
    'phoneCode': '+1767',
    'mask': '### ####',
    'minLength': 7,
  },
  {
    'name': 'Marshall Islands',
    'isoCode': 'MH',
    'phoneCode': '+692',
    'mask': '### ####',
    'minLength': 7,
  },
  {
    'name': 'China',
    'isoCode': 'CN',
    'phoneCode': '+86',
    'mask': '## ##### #####',
    'minLength': 10,
  },
  {
    'name': 'Eswatini',
    'isoCode': 'SZ',
    'phoneCode': '+268',
    'mask': '## ## ####',
    'minLength': 8,
  },
  {
    'name': 'Liechtenstein',
    'isoCode': 'LI',
    'phoneCode': '+423',
    'mask': '### ### ####',
    'minLength': 10,
  },
  {
    'name': 'Zimbabwe',
    'isoCode': 'ZW',
    'phoneCode': '+263',
    'mask': '# ######',
    'minLength': 7,
  },
  {
    'name': 'Burundi',
    'isoCode': 'BI',
    'phoneCode': '+257',
    'mask': '## ## ####',
    'minLength': 8,
  },
  {
    'name': 'Cocos Islands',
    'isoCode': 'CC',
    'phoneCode': '+61',
    'mask': '# #### ####',
    'minLength': 9,
  },
  {
    'name': 'Palau',
    'isoCode': 'PW',
    'phoneCode': '+680',
    'mask': '### ####',
    'minLength': 7,
  },
  {
    'name': 'Thailand',
    'isoCode': 'TH',
    'phoneCode': '+66',
    'mask': '## ### ####',
    'minLength': 8,
  },
  {
    'name': 'Jersey',
    'isoCode': 'JE',
    'phoneCode': '+44',
    'mask': '#### #### ######',
    'minLength': 14,
  },
  {
    'name': 'Mauritania',
    'isoCode': 'MR',
    'phoneCode': '+222',
    'mask': '## ## ####',
    'minLength': 8,
  },
  {
    'name': 'Saint Barthélemy',
    'isoCode': 'BL',
    'phoneCode': '+590',
    'mask': '### ## ## ##',
    'minLength': 9,
  },
  {
    'name': 'Algeria',
    'isoCode': 'DZ',
    'phoneCode': '+213',
    'mask': '## ### ####',
    'minLength': 9,
  },
  {
    'name': 'Kiribati',
    'isoCode': 'KI',
    'phoneCode': '+686',
    'mask': '## ###',
    'minLength': 5,
  },
  {
    'name': 'Cyprus',
    'isoCode': 'CY',
    'phoneCode': '+357',
    'mask': '## ### ###',
    'minLength': 8,
  },
  {
    'name': 'Hungary',
    'isoCode': 'HU',
    'phoneCode': '+36',
    'mask': '### ### ###',
    'minLength': 9,
  },
  {
    'name': 'Malawi',
    'isoCode': 'MW',
    'phoneCode': '+265',
    'mask': '# #### ####',
    'minLength': 6,
  },
  {
    'name': 'Bulgaria',
    'isoCode': 'BG',
    'phoneCode': '+359',
    'mask': '### ### ###',
    'minLength': 9,
  },
  {
    'name': 'South Korea',
    'isoCode': 'KR',
    'phoneCode': '+82',
    'mask': '## ### ####',
    'minLength': 9,
  },
  {
    'name': 'Belize',
    'isoCode': 'BZ',
    'phoneCode': '+501',
    'mask': '### ####',
    'minLength': 7,
  },
  {
    'name': 'Senegal',
    'isoCode': 'SN',
    'phoneCode': '+221',
    'mask': '## ### ####',
    'minLength': 9,
  },
  {
    'name': 'Grenada',
    'isoCode': 'GD',
    'phoneCode': '+1473',
    'mask': '### ####',
    'minLength': 7,
  },
  {
    'name': 'Romania',
    'isoCode': 'RO',
    'phoneCode': '+40',
    'mask': '## ### ####',
    'minLength': 9,
  },
  {
    'name': 'Kuwait',
    'isoCode': 'KW',
    'phoneCode': '+965',
    'mask': '#### ####',
    'minLength': 8,
  },
  {
    'name': 'Morocco',
    'isoCode': 'MA',
    'phoneCode': '+212',
    'mask': '## #### ###',
    'minLength': 9,
  },
  {
    'name': 'Seychelles',
    'isoCode': 'SC',
    'phoneCode': '+248',
    'mask': '# ### ###',
    'minLength': 7,
  },
  {
    'name': 'Gabon',
    'isoCode': 'GA',
    'phoneCode': '+241',
    'mask': '# ## ## ##',
    'minLength': 7,
  },
  {
    'name': 'Azerbaijan',
    'isoCode': 'AZ',
    'phoneCode': '+994',
    'mask': '## ### ## ##',
    'minLength': 9,
  },
  {
    'name': 'Aruba',
    'isoCode': 'AW',
    'phoneCode': '+297',
    'mask': '### ####',
    'minLength': 7,
  },
  {
    'name': 'Guinea-Bissau',
    'isoCode': 'GW',
    'phoneCode': '+245',
    'mask': '# ######',
    'minLength': 7,
  },
  {
    'name': 'Isle of Man',
    'isoCode': 'IM',
    'phoneCode': '+44',
    'mask': '#### ######',
    'minLength': 10,
  },
  {
    'name': 'Guadeloupe',
    'isoCode': 'GP',
    'phoneCode': '+590',
    'mask': '### ### ###',
    'minLength': 9,
  },
  {
    'name': 'Brunei',
    'isoCode': 'BN',
    'phoneCode': '+673',
    'mask': '### ####',
    'minLength': 7,
  },
  {
    'name': 'Venezuela',
    'isoCode': 'VE',
    'phoneCode': '+58',
    'mask': '### ### ####',
    'minLength': 10,
  },
  {
    'name': 'Netherlands',
    'isoCode': 'NL',
    'phoneCode': '+31',
    'mask': '## ### ####',
    'minLength': 9,
  },
  {
    'name': 'Egypt',
    'isoCode': 'EG',
    'phoneCode': '+20',
    'mask': '### ### ####',
    'minLength': 10,
  },
  {
    'name': 'Nigeria',
    'isoCode': 'NG',
    'phoneCode': '+234',
    'mask': '### ### ####',
    'minLength': 7,
  },
  {
    'name': 'French Guiana',
    'isoCode': 'GF',
    'phoneCode': '+594',
    'mask': '##### ####',
    'minLength': 9,
  },
  {
    'name': 'Mayotte',
    'isoCode': 'YT',
    'phoneCode': '+262',
    'mask': '##### ####',
    'minLength': 9,
  },
  {
    'name': 'Turkey',
    'isoCode': 'TR',
    'phoneCode': '+90',
    'mask': '### ### ####',
    'minLength': 10,
  },
  {
    'name': 'Faroe Islands',
    'isoCode': 'FO',
    'phoneCode': '+298',
    'mask': '### ###',
    'minLength': 6,
  },
  {
    'name': 'Martinique',
    'isoCode': 'MQ',
    'phoneCode': '+596',
    'mask': '### ## ## ##',
    'minLength': 9,
  },
  {
    'name': 'Wallis and Futuna',
    'isoCode': 'WF',
    'phoneCode': '+681',
    'mask': '## ####',
    'minLength': 6,
  },
  {
    'name': 'Fiji',
    'isoCode': 'FJ',
    'phoneCode': '+679',
    'mask': '## #####',
    'minLength': 7,
  },
  {
    'name': 'Christmas Island',
    'isoCode': 'CX',
    'phoneCode': '+61',
    'mask': '# #### ####',
    'minLength': 9,
  },
  {
    'name': 'British Virgin Islands',
    'isoCode': 'VG',
    'phoneCode': '+1284',
    'mask': '### ####',
    'minLength': 7,
  },
  {
    'name': 'Timor-Leste',
    'isoCode': 'TL',
    'phoneCode': '+670',
    'mask': '### ####',
    'minLength': 6,
  },
  {
    'name': 'Maldives',
    'isoCode': 'MV',
    'phoneCode': '+960',
    'mask': '### ####',
    'minLength': 7,
  },
  {
    'name': 'Antigua and Barbuda',
    'isoCode': 'AG',
    'phoneCode': '+1268',
    'mask': '### ####',
    'minLength': 7,
  },
  {
    'name': 'Turks and Caicos Islands',
    'isoCode': 'TC',
    'phoneCode': '+1649',
    'mask': '### ###',
    'minLength': 6,
  },
  {
    'name': 'Nicaragua',
    'isoCode': 'NI',
    'phoneCode': '+505',
    'mask': '#### ####',
    'minLength': 8,
  },
  {
    'name': 'South Africa',
    'isoCode': 'ZA',
    'phoneCode': '+27',
    'mask': '## ### ####',
    'minLength': 9,
  },
  {
    'name': 'Uganda',
    'isoCode': 'UG',
    'phoneCode': '+256',
    'mask': '### ### ###',
    'minLength': 9,
  },
  {
    'name': 'Cabo Verde',
    'isoCode': 'CV',
    'phoneCode': '+238',
    'mask': '### ## ##',
    'minLength': 7,
  },
  {
    'name': 'Solomon Islands',
    'isoCode': 'SB',
    'phoneCode': '+677',
    'mask': '### ####',
    'minLength': 5,
  },
  {
    'name': 'Laos',
    'isoCode': 'LA',
    'phoneCode': '+856',
    'mask': '## ### ###',
    'minLength': 8,
  },
  {
    'name': 'Montenegro',
    'isoCode': 'ME',
    'phoneCode': '+382',
    'mask': '## ### ###',
    'minLength': 8,
  },
  {
    'name': 'Cook Islands',
    'isoCode': 'CK',
    'phoneCode': '+682',
    'mask': '## ###',
    'minLength': 5,
  },
  {
    'name': 'Singapore',
    'isoCode': 'SG',
    'phoneCode': '+65',
    'mask': '#### ####',
    'minLength': 8,
  },
  {
    'name': 'Dominican Republic',
    'isoCode': 'DO',
    'phoneCode': '+1',
    'mask': '### ####',
    'minLength': 7,
  },
  {
    'name': 'Bhutan',
    'isoCode': 'BT',
    'phoneCode': '+975',
    'mask': '# ### ###',
    'minLength': 6,
  },
  {
    'name': 'Chile',
    'isoCode': 'CL',
    'phoneCode': '+56',
    'mask': '# #### ####',
    'minLength': 9,
  },
  {
    'name': 'Sint Maarten',
    'isoCode': 'SX',
    'phoneCode': '+1721',
    'mask': '### ####',
    'minLength': 7,
  },
  {
    'name': 'Sri Lanka',
    'isoCode': 'LK',
    'phoneCode': '+94',
    'mask': '## ### ####',
    'minLength': 9,
  },
  {
    'name': 'Macao',
    'isoCode': 'MO',
    'phoneCode': '+853',
    'mask': '#### ####',
    'minLength': 8,
  },
  {
    'name': 'Bolivia',
    'isoCode': 'BO',
    'phoneCode': '+591',
    'mask': '# ### ####',
    'minLength': 8,
  },
  {
    'name': 'Czech Republic',
    'isoCode': 'CZ',
    'phoneCode': '+420',
    'mask': '### ### ###',
    'minLength': 9,
  },
  {
    'name': 'Malta',
    'isoCode': 'MT',
    'phoneCode': '+356',
    'mask': '#### ####',
    'minLength': 8,
  },
  {
    'name': 'Barbados',
    'isoCode': 'BB',
    'phoneCode': '+1246',
    'mask': '### ####',
    'minLength': 7,
  },
  {
    'name': 'El Salvador',
    'isoCode': 'SV',
    'phoneCode': '+503',
    'mask': '## ## ####',
    'minLength': 8,
  },
  {
    'name': 'Poland',
    'isoCode': 'PL',
    'phoneCode': '+48',
    'mask': '### ### ###',
    'minLength': 9,
  },
  {
    'name': 'United Arab Emirates',
    'isoCode': 'AE',
    'phoneCode': '+971',
    'mask': '# ### ####',
    'minLength': 8,
  },
  {
    'name': 'Slovakia',
    'isoCode': 'SK',
    'phoneCode': '+421',
    'mask': '### ### ###',
    'minLength': 9,
  },
  {
    'name': 'Guyana',
    'isoCode': 'GY',
    'phoneCode': '+592',
    'mask': '### ####',
    'minLength': 7,
  },
  {
    'name': 'Pakistan',
    'isoCode': 'PK',
    'phoneCode': '+92',
    'mask': '### ### ####',
    'minLength': 10,
  },
  {
    'name': 'Iceland',
    'isoCode': 'IS',
    'phoneCode': '+354',
    'mask': '### ####',
    'minLength': 7,
  },
  {
    'name': 'Sierra Leone',
    'isoCode': 'SL',
    'phoneCode': '+232',
    'mask': '## ######',
    'minLength': 8,
  },
  {
    'name': 'Croatia',
    'isoCode': 'HR',
    'phoneCode': '+385',
    'mask': '## ### ###',
    'minLength': 8,
  },
  {
    'name': 'French Polynesia',
    'isoCode': 'PF',
    'phoneCode': '+689',
    'mask': '## ## ##',
    'minLength': 6,
  },
  {
    'name': 'Bahamas',
    'isoCode': 'BS',
    'phoneCode': '+1242',
    'mask': '### ####',
    'minLength': 7,
  },
  {
    'name': 'Saudi Arabia',
    'isoCode': 'SA',
    'phoneCode': '+966',
    'mask': '# #### ####',
    'minLength': 8,
  },
  {
    'name': 'Ireland',
    'isoCode': 'IE',
    'phoneCode': '+353',
    'mask': '### ### ###',
    'minLength': 9,
  },
  {
    'name': 'Ghana',
    'isoCode': 'GH',
    'phoneCode': '+233',
    'mask': '### ### ###',
    'minLength': 9,
  },
  {
    'name': 'Falkland Islands',
    'isoCode': 'FK',
    'phoneCode': '+500',
    'mask': '#####',
    'minLength': 5,
  },
  {
    'name': 'British Indian Ocean Territory',
    'isoCode': 'IO',
    'phoneCode': '+246',
    'mask': '### ####',
    'minLength': 7,
  },
  {
    'name': 'Norway',
    'isoCode': 'NO',
    'phoneCode': '+47',
    'mask': '### ## ###',
    'minLength': 8,
  },
  {
    'name': 'Honduras',
    'isoCode': 'HN',
    'phoneCode': '+504',
    'mask': '#### ####',
    'minLength': 8,
  },
  {
    'name': 'Saint Vincent and the Grenadines',
    'isoCode': 'VC',
    'phoneCode': '+1784',
    'mask': '### ####',
    'minLength': 7,
  },
  {
    'name': 'Italy',
    'isoCode': 'IT',
    'phoneCode': '+39',
    'mask': '### #### ###',
    'minLength': 10,
  },
  {
    'name': 'Vietnam',
    'isoCode': 'VN',
    'phoneCode': '+84',
    'mask': '### #### ###',
    'minLength': 9,
  },
  {
    'name': 'Togo',
    'isoCode': 'TG',
    'phoneCode': '+228',
    'mask': '## ### ###',
    'minLength': 8,
  },
  {
    'name': 'Niger',
    'isoCode': 'NE',
    'phoneCode': '+227',
    'mask': '## ## ####',
    'minLength': 8,
  },
  {
    'name': 'Spain',
    'isoCode': 'ES',
    'phoneCode': '+34',
    'mask': '### ### ###',
    'minLength': 9,
  },
  {
    'name': 'Tanzania',
    'isoCode': 'TZ',
    'phoneCode': '+255',
    'mask': '## ### ####',
    'minLength': 9,
  },
  {
    'name': 'Colombia',
    'isoCode': 'CO',
    'phoneCode': '+57',
    'mask': '### ### ####',
    'minLength': 10,
  },
  {
    'name': 'Mongolia',
    'isoCode': 'MN',
    'phoneCode': '+976',
    'mask': '## ## ####',
    'minLength': 8,
  },
  {
    'name': 'Trinidad and Tobago',
    'isoCode': 'TT',
    'phoneCode': '+1868',
    'mask': '### ####',
    'minLength': 7,
  },
  {
    'name': 'Angola',
    'isoCode': 'AO',
    'phoneCode': '+244',
    'mask': '### ### ###',
    'minLength': 9,
  },
  {
    'name': 'Micronesia',
    'isoCode': 'FM',
    'phoneCode': '+691',
    'mask': '### ####',
    'minLength': 7,
  },
  {
    'name': 'Tokelau',
    'isoCode': 'TK',
    'phoneCode': '+690',
    'mask': '####',
    'minLength': 4,
  },
  {
    'name': 'Montserrat',
    'isoCode': 'MS',
    'phoneCode': '+1664',
    'mask': '### ####',
    'minLength': 7,
  },
  {
    'name': 'Andorra',
    'isoCode': 'AD',
    'phoneCode': '+376',
    'mask': '### ###',
    'minLength': 6,
  },
  {
    'name': 'Tunisia',
    'isoCode': 'TN',
    'phoneCode': '+216',
    'mask': '## ### ###',
    'minLength': 8,
  },
  {
    'name': 'Jordan',
    'isoCode': 'JO',
    'phoneCode': '+962',
    'mask': '# #### ####',
    'minLength': 9,
  },
  {
    'name': 'Mexico',
    'isoCode': 'MX',
    'phoneCode': '+52',
    'mask': '### ### ####',
    'minLength': 8,
  },
  {
    'name': 'Burkina Faso',
    'isoCode': 'BF',
    'phoneCode': '+226',
    'mask': '## ## ####',
    'minLength': 8,
  },
  {
    'name': 'Uruguay',
    'isoCode': 'UY',
    'phoneCode': '+598',
    'mask': '# ### ## ##',
    'minLength': 8,
  },
  {
    'name': 'Saint Lucia',
    'isoCode': 'LC',
    'phoneCode': '+1758',
    'mask': '### ####',
    'minLength': 7,
  },
  {
    'name': 'Djibouti',
    'isoCode': 'DJ',
    'phoneCode': '+253',
    'mask': '## ## ## ##',
    'minLength': 8,
  },
  {
    'name': 'Cayman Islands',
    'isoCode': 'KY',
    'phoneCode': '+1345',
    'mask': '### ####',
    'minLength': 7,
  },
  {
    'name': 'Madagascar',
    'isoCode': 'MG',
    'phoneCode': '+261',
    'mask': '## ## #####',
    'minLength': 9,
  },
  {
    'name': 'Botswana',
    'isoCode': 'BW',
    'phoneCode': '+267',
    'mask': '## ### ###',
    'minLength': 8,
  },
  {
    'name': 'Sweden',
    'isoCode': 'SE',
    'phoneCode': '+46',
    'mask': '## ### ####',
    'minLength': 9,
  },
  {
    'name': 'Zambia',
    'isoCode': 'ZM',
    'phoneCode': '+260',
    'mask': '## ### ####',
    'minLength': 9,
  },
  {
    'name': 'Paraguay',
    'isoCode': 'PY',
    'phoneCode': '+595',
    'mask': '### ### ###',
    'minLength': 9,
  },
  {
    'name': 'Benin',
    'isoCode': 'BJ',
    'phoneCode': '+229',
    'mask': '## ## ####',
    'minLength': 8,
  },
  {
    'name': 'Kyrgyzstan',
    'isoCode': 'KG',
    'phoneCode': '+996',
    'mask': '### ### ###',
    'minLength': 9,
  },
  {
    'name': 'Armenia',
    'isoCode': 'AM',
    'phoneCode': '+374',
    'mask': '## ### ###',
    'minLength': 8,
  },
  {
    'name': 'Portugal',
    'isoCode': 'PT',
    'phoneCode': '+351',
    'mask': '## ### ####',
    'minLength': 9,
  },
  {
    'name': 'Equatorial Guinea',
    'isoCode': 'GQ',
    'phoneCode': '+240',
    'mask': '## ### ####',
    'minLength': 9,
  },
  {
    'name': 'Bermuda',
    'isoCode': 'BM',
    'phoneCode': '+1441',
    'mask': '### ####',
    'minLength': 7,
  },
  {
    'name': 'South Sudan',
    'isoCode': 'SS',
    'phoneCode': '+211',
    'mask': '## ### ####',
    'minLength': 9,
  },
  {
    'name': 'Cambodia',
    'isoCode': 'KH',
    'phoneCode': '+855',
    'mask': '## ### ###',
    'minLength': 8,
  },
  {
    'name': 'Palestine',
    'isoCode': 'PS',
    'phoneCode': '+970',
    'mask': '## ### ####',
    'minLength': 9,
  },
  {
    'name': 'Sao Tome and Principe',
    'isoCode': 'ST',
    'phoneCode': '+239',
    'mask': '## #####',
    'minLength': 7,
  },
  {
    'name': 'Comoros',
    'isoCode': 'KM',
    'phoneCode': '+269',
    'mask': '## #####',
    'minLength': 7,
  },
  {
    'name': 'Slovenia',
    'isoCode': 'SI',
    'phoneCode': '+386',
    'mask': '## ### ###',
    'minLength': 8,
  },
  {
    'name': 'Guernsey',
    'isoCode': 'GG',
    'phoneCode': '+44',
    'mask': '#### ######',
    'minLength': 10,
  },
  {
    'name': 'Peru',
    'isoCode': 'PE',
    'phoneCode': '+51',
    'mask': '### ### ###',
    'minLength': 9,
  },
  {
    'name': 'Namibia',
    'isoCode': 'NA',
    'phoneCode': '+264',
    'mask': '## ### ####',
    'minLength': 9,
  }
];
