import 'package:blueprint/features/countries/models/country.dart';

final rawCountries = <Map<String, dynamic>>[
  {
    'name': 'Qatar',
    'isoCode': 'QA',
    'phoneCode': '+974',
    'mask': '#### ####',
    'minLength': 8,
  },
  {
    'name': 'Costa Rica',
    'isoCode': 'CR',
    'phoneCode': '+506',
    'mask': '#### ####',
    'minLength': 8,
  },
  {
    'name': 'Russia',
    'isoCode': 'RU',
    'phoneCode': '+7',
    'mask': '### ### ## ##',
    'minLength': 10,
  },
  {
    'name': 'Holy See',
    'isoCode': 'VA',
    'phoneCode': '+39',
    'mask': '#####',
    'minLength': 5,
  },
  {
    'name': 'Ukraine',
    'isoCode': 'UA',
    'phoneCode': '+380',
    'mask': '## ### ## ##',
    'minLength': 9,
  },
  {
    'name': 'Lithuania',
    'isoCode': 'LT',
    'phoneCode': '+370',
    'mask': '### ## ###',
    'minLength': 8,
  },
  {
    'name': 'Afghanistan',
    'isoCode': 'AF',
    'phoneCode': '+93',
    'mask': '## ### ####',
    'minLength': 9,
  },
  {
    'name': 'Saint Helena, Ascension and Tristan da Cunha',
    'isoCode': 'SH',
    'phoneCode': '+290',
    'mask': '####',
    'minLength': 4,
  },
  {
    'name': 'Jamaica',
    'isoCode': 'JM',
    'phoneCode': '+1876',
    'mask': '### ####',
    'minLength': 7,
  },
  {
    'name': 'France',
    'isoCode': 'FR',
    'phoneCode': '+33',
    'mask': '### ### ###',
    'minLength': 9,
  },
  {
    'name': 'Chad',
    'isoCode': 'TD',
    'phoneCode': '+235',
    'mask': '## ## ## ##',
    'minLength': 8,
  },
  {
    'name': 'Norfolk Island',
    'isoCode': 'NF',
    'phoneCode': '+672',
    'mask': '## ###',
    'minLength': 5,
  },
  {
    'name': 'Uzbekistan',
    'isoCode': 'UZ',
    'phoneCode': '+998',
    'mask': '## ### ####',
    'minLength': 9,
  },
  {
    'name': 'Monaco',
    'isoCode': 'MC',
    'phoneCode': '+377',
    'mask': '### ### ###',
    'minLength': 8,
  },
  {
    'name': 'Cuba',
    'isoCode': 'CU',
    'phoneCode': '+53',
    'mask': '# ### ####',
    'minLength': 8,
  },
  {
    'name': 'Austria',
    'isoCode': 'AT',
    'phoneCode': '+43',
    'mask': '### ### ####',
    'minLength': 10,
  },
  {
    'name': 'Dominica',
    'isoCode': 'DM',
    'phoneCode': '+1767',
    'mask': '### ####',
    'minLength': 7,
  },
  {
    'name': 'Marshall Islands',
    'isoCode': 'MH',
    'phoneCode': '+692',
    'mask': '### ####',
    'minLength': 7,
  },
  {
    'name': 'China',
    'isoCode': 'CN',
    'phoneCode': '+86',
    'mask': '## ##### #####',
    'minLength': 10,
  },
  {
    'name': 'Eswatini',
    'isoCode': 'SZ',
    'phoneCode': '+268',
    'mask': '## ## ####',
    'minLength': 8,
  },
  {
    'name': 'Liechtenstein',
    'isoCode': 'LI',
    'phoneCode': '+423',
    'mask': '### ### ####',
    'minLength': 10,
  },
  {
    'name': 'Zimbabwe',
    'isoCode': 'ZW',
    'phoneCode': '+263',
    'mask': '# ######',
    'minLength': 7,
  },
  {
    'name': 'Burundi',
    'isoCode': 'BI',
    'phoneCode': '+257',
    'mask': '## ## ####',
    'minLength': 8,
  },
  {
    'name': 'Cocos Islands',
    'isoCode': 'CC',
    'phoneCode': '+61',
    'mask': '# #### ####',
    'minLength': 9,
  },
  {
    'name': 'Palau',
    'isoCode': 'PW',
    'phoneCode': '+680',
    'mask': '### ####',
    'minLength': 7,
  },
  {
    'name': 'Thailand',
    'isoCode': 'TH',
    'phoneCode': '+66',
    'mask': '## ### ####',
    'minLength': 8,
  },
  {
    'name': 'Jersey',
    'isoCode': 'JE',
    'phoneCode': '+44',
    'mask': '#### #### ######',
    'minLength': 14,
  },
  {
    'name': 'Mauritania',
    'isoCode': 'MR',
    'phoneCode': '+222',
    'mask': '## ## ####',
    'minLength': 8,
  },
  {
    'name': 'Saint Barthélemy',
    'isoCode': 'BL',
    'phoneCode': '+590',
    'mask': '### ## ## ##',
    'minLength': 9,
  },
  {
    'name': 'Algeria',
    'isoCode': 'DZ',
    'phoneCode': '+213',
    'mask': '## ### ####',
    'minLength': 9,
  },
  {
    'name': 'Mexico',
    'isoCode': 'MX',
    'phoneCode': '+52',
    'mask': '### ### ####',
    'minLength': 8,
  },
  {
    'name': 'Burkina Faso',
    'isoCode': 'BF',
    'phoneCode': '+226',
    'mask': '## ## ####',
    'minLength': 8,
  },
  {
    'name': 'Uruguay',
    'isoCode': 'UY',
    'phoneCode': '+598',
    'mask': '# ### ## ##',
    'minLength': 8,
  },
  {
    'name': 'Saint Lucia',
    'isoCode': 'LC',
    'phoneCode': '+1758',
    'mask': '### ####',
    'minLength': 7,
  },
  {
    'name': 'Djibouti',
    'isoCode': 'DJ',
    'phoneCode': '+253',
    'mask': '## ## ## ##',
    'minLength': 8,
  },
  {
    'name': 'Cayman Islands',
    'isoCode': 'KY',
    'phoneCode': '+1345',
    'mask': '### ####',
    'minLength': 7,
  },
  {
    'name': 'Madagascar',
    'isoCode': 'MG',
    'phoneCode': '+261',
    'mask': '## ## #####',
    'minLength': 9,
  },
  {
    'name': 'Botswana',
    'isoCode': 'BW',
    'phoneCode': '+267',
    'mask': '## ### ###',
    'minLength': 8,
  },
  {
    'name': 'Sweden',
    'isoCode': 'SE',
    'phoneCode': '+46',
    'mask': '## ### ####',
    'minLength': 9,
  },
  {
    'name': 'Zambia',
    'isoCode': 'ZM',
    'phoneCode': '+260',
    'mask': '## ### ####',
    'minLength': 9,
  },
  {
    'name': 'Paraguay',
    'isoCode': 'PY',
    'phoneCode': '+595',
    'mask': '### ### ###',
    'minLength': 9,
  },
  {
    'name': 'Benin',
    'isoCode': 'BJ',
    'phoneCode': '+229',
    'mask': '## ## ####',
    'minLength': 8,
  },
  {
    'name': 'Kyrgyzstan',
    'isoCode': 'KG',
    'phoneCode': '+996',
    'mask': '### ### ###',
    'minLength': 9,
  },
  {
    'name': 'Armenia',
    'isoCode': 'AM',
    'phoneCode': '+374',
    'mask': '## ### ###',
    'minLength': 8,
  },
  {
    'name': 'Portugal',
    'isoCode': 'PT',
    'phoneCode': '+351',
    'mask': '## ### ####',
    'minLength': 9,
  },
  {
    'name': 'Equatorial Guinea',
    'isoCode': 'GQ',
    'phoneCode': '+240',
    'mask': '## ### ####',
    'minLength': 9,
  },
  {
    'name': 'Bermuda',
    'isoCode': 'BM',
    'phoneCode': '+1441',
    'mask': '### ####',
    'minLength': 7,
  },
  {
    'name': 'South Sudan',
    'isoCode': 'SS',
    'phoneCode': '+211',
    'mask': '## ### ####',
    'minLength': 9,
  },
  {
    'name': 'Cambodia',
    'isoCode': 'KH',
    'phoneCode': '+855',
    'mask': '## ### ###',
    'minLength': 8,
  },
  {
    'name': 'Palestine',
    'isoCode': 'PS',
    'phoneCode': '+970',
    'mask': '## ### ####',
    'minLength': 9,
  },
  {
    'name': 'Sao Tome and Principe',
    'isoCode': 'ST',
    'phoneCode': '+239',
    'mask': '## #####',
    'minLength': 7,
  },
  {
    'name': 'Comoros',
    'isoCode': 'KM',
    'phoneCode': '+269',
    'mask': '## #####',
    'minLength': 7,
  },
  {
    'name': 'Slovenia',
    'isoCode': 'SI',
    'phoneCode': '+386',
    'mask': '## ### ###',
    'minLength': 8,
  },
  {
    'name': 'Guernsey',
    'isoCode': 'GG',
    'phoneCode': '+44',
    'mask': '#### ######',
    'minLength': 10,
  },
  {
    'name': 'Peru',
    'isoCode': 'PE',
    'phoneCode': '+51',
    'mask': '### ### ###',
    'minLength': 9,
  },
  {
    'name': 'Namibia',
    'isoCode': 'NA',
    'phoneCode': '+264',
    'mask': '## ### ####',
    'minLength': 9,
  }
];

List<Country> countries() {
  return rawCountries
      .map(
        (e) => Country(
          name: e['name'] as String,
          isoCode: e['isoCode'] as String,
          phoneCode: e['phoneCode'] as String,
          mask: e['mask'] as String,
          minLength: e['minLength'] as int,
        ),
      )
      .toList()
    ..sort((a, b) => a.name.compareTo(b.name));
}
